### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by fawaleb**
#### Use pycryptodome instead of pycrypto

### CODE REVIEW

**Comment by fontanon** [comment]
Hi @fawaleb !!

Thanks for the contribution. 

I've to admit there was already the PR #2 on python3 porting. But I didn't attended it :disappointed: (my fault).

However, I tried to review yours and I cannot make it work, have a look at full downloading and testing from your repo:

```
fontanon@baphomet:~/borrame$ git clone https://github.com/fawaleb/kiopcgenerator.git
Cloning into 'kiopcgenerator'...
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 115 (delta 29), reused 63 (delta 26), pack-reused 47
Receiving objects: 100% (115/115), 26.97 KiB | 6.74 MiB/s, done.
Resolving deltas: 100% (49/49), done.
fontanon@baphomet:~/borrame$ cd kiopcgenerator/
fontanon@baphomet:~/borrame/kiopcgenerator$ git br PYTHON3
fontanon@baphomet:~/borrame/kiopcgenerator$ git co PYTHON3
Switched to branch 'PYTHON3'
fontanon@baphomet:~/borrame/kiopcgenerator$ git pull origin PYTHON3
From https://github.com/fawaleb/kiopcgenerator
 * branch            PYTHON3    -> FETCH_HEAD
Updating 0fce60c..39f1cd5
Fast-forward
 kiopcgenerator/lib.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)
fontanon@baphomet:~/borrame/kiopcgenerator$ ls
kiopcgen  kiopcgenerator  LICENSE  Pipfile  README.md  requirements.txt  setup.cfg  setup.py
fontanon@baphomet:~/borrame/kiopcgenerator$ python3 -m venv .env
fontanon@baphomet:~/borrame/kiopcgenerator$ source .env/bin/activate

(.env) fontanon@baphomet:~/borrame/kiopcgenerator$ pip3 install -r requirements.txt 
Collecting pycryptodome==3.9.9
  Using cached pycryptodome-3.9.9-cp38-cp38-manylinux1_x86_64.whl (13.7 MB)
Collecting uuid==1.30
  Using cached uuid-1.30.tar.gz (5.8 kB)
Building wheels for collected packages: uuid
  Building wheel for uuid (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/fontanon/Downloads/kiopcgenerator/.env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k9g06r1c/uuid/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k9g06r1c/uuid/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-oug9hclj
       cwd: /tmp/pip-install-k9g06r1c/uuid/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for uuid
  Running setup.py clean for uuid
Failed to build uuid
Installing collected packages: pycryptodome, uuid
    Running setup.py install for uuid ... done
Successfully installed pycryptodome-3.9.9 uuid-1.30

(.env) fontanon@baphomet:~/borrame/kiopcgenerator$ python setup.py install
running install
running bdist_egg
running egg_info
creating kiopcgenerator.egg-info
writing kiopcgenerator.egg-info/PKG-INFO
writing dependency_links to kiopcgenerator.egg-info/dependency_links.txt
writing top-level names to kiopcgenerator.egg-info/top_level.txt
writing manifest file 'kiopcgenerator.egg-info/SOURCES.txt'
reading manifest file 'kiopcgenerator.egg-info/SOURCES.txt'
writing manifest file 'kiopcgenerator.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/kiopcgenerator
copying kiopcgenerator/__init__.py -> build/lib/kiopcgenerator
copying kiopcgenerator/lib.py -> build/lib/kiopcgenerator
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/kiopcgenerator
copying build/lib/kiopcgenerator/__init__.py -> build/bdist.linux-x86_64/egg/kiopcgenerator
copying build/lib/kiopcgenerator/lib.py -> build/bdist.linux-x86_64/egg/kiopcgenerator
byte-compiling build/bdist.linux-x86_64/egg/kiopcgenerator/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/kiopcgenerator/lib.py to lib.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.8
copying and adjusting kiopcgen -> build/scripts-3.8
changing mode of build/scripts-3.8/kiopcgen from 664 to 775
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.8/kiopcgen -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/kiopcgen to 775
copying kiopcgenerator.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kiopcgenerator.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kiopcgenerator.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kiopcgenerator.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/kiopcgenerator-0.1.4-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing kiopcgenerator-0.1.4-py3.8.egg
Copying kiopcgenerator-0.1.4-py3.8.egg to /home/fontanon/Downloads/kiopcgenerator/.env/lib/python3.8/site-packages
Adding kiopcgenerator 0.1.4 to easy-install.pth file
Installing kiopcgen script to /home/fontanon/Downloads/kiopcgenerator/.env/bin

Installed /home/fontanon/Downloads/kiopcgenerator/.env/lib/python3.8/site-packages/kiopcgenerator-0.1.4-py3.8.egg
Processing dependencies for kiopcgenerator==0.1.4
Finished processing dependencies for kiopcgenerator==0.1.4

(.env) fontanon@baphomet:~/borrame/kiopcgenerator$ kiopcgen  -o D7DECB1F50404CC29ECBF989FE73AFC5 -t 2257CC6E9746434B89F346F0276CCAEC
Traceback (most recent call last):
  File "/home/fontanon/Downloads/kiopcgenerator/.env/bin/kiopcgen", line 4, in <module>
    __import__('pkg_resources').run_script('kiopcgenerator==0.1.4', 'kiopcgen')
  File "/home/fontanon/Downloads/kiopcgenerator/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/fontanon/Downloads/kiopcgenerator/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/home/fontanon/Downloads/kiopcgenerator/.env/lib/python3.8/site-packages/kiopcgenerator-0.1.4-py3.8.egg/EGG-INFO/scripts/kiopcgen", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/fontanon/Downloads/kiopcgenerator/.env/lib/python3.8/site-packages/kiopcgenerator-0.1.4-py3.8.egg/kiopcgenerator/__init__.py", line 9, in <module>
ModuleNotFoundError: No module named 'lib'
(.env) fontanon@baphomet:~/borrame/kiopcgenerator$ 
```

**Comment by fontanon** [comment]
I see the advantage of migrating from `pycrypto` to `pycryptodome` so if you want to do it on the top of the current `master` branch I'll accept the PR straightaway.

**Comment by fawaleb** [comment]
I have updated __init__.py to reference .lib
Please try again.

**Comment by fontanon** [comment]
Worked like a charm! Great update! I'm merging now. Thanks @fawaleb !!

**Pull request merged**
